# Generated by Django 2.2.7 on 2019-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('is_individual', models.BooleanField(blank=True, default=True)),
                ('sys_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
