# Generated by Django 2.2.7 on 2019-11-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191125_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sys_company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='system.Company'),
        ),
    ]
