# Generated by Django 2.2.7 on 2019-11-25 14:23

from django.db import migrations, models
import django.db.models.deletion
import system.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=5)),
            ],
            bases=(system.utils.NameAsStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_contra_account', models.BooleanField(blank=True, default=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.AccountType')),
                ('sys_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
