# Generated by Django 2.2.7 on 2019-11-25 16:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('accounting', '0003_auto_20191125_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series', models.SmallIntegerField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('sys_company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='is_cash_account',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_type', models.CharField(max_length=20)),
                ('source_reference', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='accounting.Account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounting.Journal')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
