# Generated by Django 2.2.7 on 2019-11-26 00:19

from django.db import migrations, models
import django.db.models.deletion
import system.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sys_company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
            ],
            options={
                'abstract': False,
            },
            bases=(system.utils.NameAsStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=200)),
                ('quantity_in', models.DecimalField(decimal_places=5, max_digits=19)),
                ('quantity_out', models.DecimalField(decimal_places=5, max_digits=19)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('date', models.DateField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('inventory_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.ItemTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=19)),
                ('costing_method', models.CharField(blank=True, choices=[('FIFO', 'First in First Out'), ('SPECIFIC', 'Specific Identifaction Method')], default='FIFO', max_length=20)),
                ('sys_company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.UnitOfMeasure')),
            ],
            options={
                'abstract': False,
            },
            bases=(system.utils.NameAsStrMixin, models.Model),
        ),
    ]
