# Generated by Django 2.2.7 on 2019-11-26 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contacts', '0003_auto_20191125_1436'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series', models.SmallIntegerField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='contacts.Contact')),
                ('sys_company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='system.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=5, max_digits=19)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=17)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='assets.Item')),
            ],
        ),
    ]
