# Generated by Django 2.2.7 on 2019-11-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currently_loggedin_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.Company'),
        ),
    ]
